<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder {
    public function run() {
        $questions = [
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 mudah 9',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 medium 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 1 hard 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],


                [
                    'question_text' => 'Pertanyaan kuis 1 hard 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],

                [
                    'question_text' => 'Pertanyaan kuis 1 hard 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 1,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 mudah 9',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 medium 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 2 hard 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 2,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 mudah 9',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 medium 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 3 hard 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 3,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 mudah 9',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'easy',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 medium 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'medium',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 1',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 2',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 3',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 4',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 5',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 6',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 7',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
                [
                    'question_text' => 'Pertanyaan kuis 4 hard 8',
                    'option_a' => 'ya',
                    'option_b' => 'tidak',
                    'option_c' => 'bisa jadi',
                    'option_d' => 'semuanya benar',
                    'correct_option' => 'A',
                    'difficulty' => 'hard',
                    'quiz_id' => 4,
                ],
            ];



        DB::table('questions')->insert($questions);
    }
}
